### ISSUE TITLE
Instructions on how to use this software

### ISSUE THREAD

**Issue by billlyzhaoyh** [plai-group/covid#1]
@andrewwarrington @saeidnp thanks for putting this on github and I am with a group of people at https://www.aiforgoodsimulator.com/ we are working with NGOs and local authorities to find out what interventions strategies could be implemented in refugee camps to help curb the spread of COVID 19 and this looks like a useful initiative. I am wondering if you guys can put up some instructions on how to run the model, that will help our modelling team immensely. If you have some bandwidth to help out as we are scaling up our efforts to work with some countries that could use modelling help as well, please get in touch with me!

**Comment by billlyzhaoyh** [comment]
The run was unsuccessful with the following errors. I only changed the population parameter from 10000 to 20000 and left the code base unchanged. Many of the plots were not produced.


 99%|██████████████████████████████████████████▌| 85/86 [07:49<00:02,  2.52s/it]Traceback (most recent call last):
  File "seir_demo.py", line 438, in <module>
    _shade=True)
  File "/Users/billyzhaoyh/Desktop/AIforGoodSimulator/covidplai/SEIR/plotting.py", line 284, in do_family_of_plots
    make_trajectory_plot(plt.gca(), noised_parameters, _visited_states, results_noise, valid_simulations, t, _plot_valid=None, _ylim=_zoom_lims, _shade=_shade)
  File "/Users/billyzhaoyh/Desktop/AIforGoodSimulator/covidplai/SEIR/plotting.py", line 143, in make_trajectory_plot
    _axe.fill_between(_t[_t_idx_current - _s_idx_current:], _lq, _uq, color='k', alpha=0.2)
  File "/Users/billyzhaoyh/anaconda/envs/aihack/lib/python3.7/site-packages/matplotlib/__init__.py", line 1599, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/billyzhaoyh/anaconda/envs/aihack/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5244, in fill_between
    map(np.ma.getmask, [x, y1, y2]))
ValueError: operands could not be broadcast together with shapes (8,) (6,) 
 99%|██████████████████████████████████████████▌| 85/86 [07:50<00:05,  5.54s/it]

**Comment by billlyzhaoyh** [comment]
Also, the codebase doesn't seem to state the R0 value directly but there are beta values and infection period. Are these estimated from the R0 values yielded from the current studies and what is the range of R0 values in the simulation? Roughly between 1-2?

**Comment by andrewwarrington** [comment]
Hi Billy, thanks for reaching out.  I just cloned the repo, made the change you implement, and had it run and produce all of the plots, so I don't know why you aren't getting the plots being produced.  The MPC plots will be a bit funny as the simulation always starts with 1 person exposed, and so within the time horizon the infection won't really have taken hold.  

The error you post is in the plotting function, at the final timestep it errors if the timestep between interventions does not divide exactly into the total time.  This doesn't effect the actual code or plotting though, other than at the final time step, and can effectively be avoided by using a try-catch statement.  I meant to get around to handling this in the plotting script, but other things got in the way.  it is on the todo list...!  

With respect to R_0, this value can be computed from other quantities as:
$R_0  = N \frac{\beta_1}{p_1 + \gamma_1} + \frac{p_1}{p_1 + \gamma_1} \left( \frac{N \beta_2}{p_2 + \gamma_2} + \frac{p_2}{p_2 + \gamma_2} \frac{N \beta_3}{\mu + \gamma_3} \right)$
and so we don't directly specify R_0.  The model itself doesn't use R_0 directly, as R_0 is derived from properties, such as infection duration, which are more easily measurable than the reproductive rate.  I will add a todo to make R_0 available as a function of the current simulation parameters or something similar.  

I hope this answers your questions.  👍
